#!/bin/bash
while true #[ $REPLY -le "4" ]
clear
echo "請輸入1-4選項:"
read
do
  case $REPLY in
	    1)
      echo "program 1"
      sleep 1
    ;;

    2)
      echo "program 2"
      sleep 1
    ;;

    3)
      echo "program 3"
      sleep 1
    ;;

    4)
      echo "end program"
      sleep 1
      exit
    ;;

    *)
      echo "請輸入1-4選項:"
      read
    ;;
  esac
done
